import Head from "next/head";
import { useContext } from "react";
import { client, SanityContex } from "@/components/SanityContextProvider";
import { NextPage } from "next";
import { Post } from "@/types/post";

const Home: NextPage = () => {
  const client = useContext(SanityContex);
  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        height: "100%",
      }}
    >
      <Head>
        <title>Next-Sanity-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          height: "50vh",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <h1>Welcome to NextJS blog with Sanity</h1>
      </div>
    </div>
  );
};
export default Home;
